name: pharmacyy
description: A new Flutter project

publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Add HTTP package for API calls
  jwt_decoder: ^2.0.1  # Add JWT decoder package to decode the JWT token
  shared_preferences: ^2.1.0  # Add shared_preferences for storing JWT tokens and other data locally
  image_picker: ^0.8.5+3  # Check for the latest version on pub.dev
  path_provider: ^2.0.11  # Optional if you need to save images locally

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Lints for better code quality

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/pic1.png
    - assets/email.png
    - assets/motdepasse.png
    - assets/back.png
    - assets/logoo.png
    - assets/menu.png
    - assets/search.png
    - assets/pharmacypic.png
    - assets/commande.png
    - assets/pharmacie.png
    - assets/accueil.png
    - assets/searchwhite.png
    - assets/upload.png
    - assets/commandewhite.png
    - assets/pharmaciewhite.png
